name: Print Info

on:
  push:
    paths:
      - 'file.txt'  # Solo se ejecuta cuando se modifica file.txt

jobs:
  print_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Name, Surname, and Hobby
        run: |
          echo "Nombre: jeronimo"
          echo "Apellido: bañol"
          echo "Hobby: hacer ejercicio, leer libros"

